# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d4a112e860a7253a88e6afedc0ff051fbe845ba9fb7910485a868b8cab3a89745926a46a8685993ae664aad632fe754e9c06ec6b36d801e69c1446e9ee45726

test:
  secret_key_base: 7897ad0fcb9738af5ce4f078108dbf59cdd38606b2c5990a331bc3266c312c89271d4f00f14f9cfb66ea152adf1416346e92f9b87afc72e98b72eaabc879ea90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
